<?xml version="1.0"?>

<!--
	conjugation-it.xml - Italian conjugation templates
	Copyright (C) 2010 Christophe Durville <http://polyglotte.tuxfamily.org>
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
	02111-1307, USA.
-->

<!DOCTYPE conjugation-it [
	<!ELEMENT conjugation-it (template+)>
	<!ELEMENT template (infinitive, indicative, conditional, subjunctive, imperative, participle, gerund)>
	<!ATTLIST template name CDATA #REQUIRED>

	<!ELEMENT infinitive (infinitive-present)>
	<!ELEMENT indicative (present, imperfect, future, simple-past)>
	<!ELEMENT conditional (present)> 
	<!ELEMENT subjunctive (present, imperfect)>
	<!ELEMENT imperative (imperative-present)>
	<!ELEMENT participle (present-participle, past-participle)>
	<!ELEMENT gerund (present-gerund)>

	<!ELEMENT infinitive-present (p)>
	<!ELEMENT present (p, p, p, p, p, p)>
	<!ELEMENT present-gerund (p)>
	<!ELEMENT imperfect (p, p, p, p, p, p)>
	<!ELEMENT future (p, p, p, p, p, p)>
	<!ELEMENT simple-past (p, p, p, p, p, p)>
	<!ELEMENT imperative-present (p, p, p, p, p)>
	<!ELEMENT present-participle (p)>
	<!ELEMENT past-participle (p, p, p, p)>

	<!ELEMENT p (i*)>
	<!ELEMENT i (#PCDATA)>
]>

<conjugation-it>

<template name="am:are">  <!-- 1er groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>are</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i>i</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>ate</i></p>
			<p><i>ano</i></p>
		</present>
		<imperfect>
			<p><i>avo</i></p>
			<p><i>avi</i></p>
			<p><i>ava</i></p>
			<p><i>avamo</i></p>
			<p><i>avate</i></p>
			<p><i>avano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>ai</i></p>
			<p><i>asti</i></p>
			<p><i>ò</i></p>
			<p><i>ammo</i></p>
			<p><i>aste</i></p>
			<p><i>arono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ino</i></p>
		</present>
		<imperfect>
			<p><i>assi</i></p>
			<p><i>assi</i></p>
			<p><i>asse</i></p>
			<p><i>assimo</i></p>
			<p><i>aste</i></p>
			<p><i>assero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>a</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>ate</i></p>
			<p><i>ino</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ante</i></p>
		</present-participle>
		<past-participle>
			<p><i>ato</i></p>
			<p><i>ati</i></p>
			<p><i>ata</i></p>
			<p><i>ate</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>ando</i></p>
		</present-gerund>
	</gerund>
</template>


<template name="mang:iare">  <!-- 1er groupe (en iare) -->
	<infinitive>
		<infinitive-present>
			<p><i>iare</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>io</i></p>
			<p><i>i</i></p>
			<p><i>ia</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>iano</i></p>
		</present>
		<imperfect>
			<p><i>iavo</i></p>
			<p><i>iavi</i></p>
			<p><i>iava</i></p>
			<p><i>iavamo</i></p>
			<p><i>iavate</i></p>
			<p><i>iavano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>iai</i></p>
			<p><i>iasti</i></p>
			<p><i>iò</i></p>
			<p><i>iammo</i></p>
			<p><i>iaste</i></p>
			<p><i>iarono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ino</i></p>
		</present>
		<imperfect>
			<p><i>iassi</i></p>
			<p><i>iassi</i></p>
			<p><i>iasse</i></p>
			<p><i>iassimo</i></p>
			<p><i>iaste</i></p>
			<p><i>iassero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>ia</i></p>
			<p><i>i</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ino</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>iante</i></p>
		</present-participle>
		<past-participle>
			<p><i>iato</i></p>
			<p><i>iati</i></p>
			<p><i>iata</i></p>
			<p><i>iate</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>iando</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="studi:are">  <!-- 1er groupe (en iare) -->
	<infinitive>
		<infinitive-present>
			<p><i>are</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i></i></p>
			<p><i>a</i></p>
			<p><i>amo</i></p>
			<p><i>ate</i></p>
			<p><i>ano</i></p>
		</present>
		<imperfect>
			<p><i>avo</i></p>
			<p><i>avi</i></p>
			<p><i>ava</i></p>
			<p><i>avamo</i></p>
			<p><i>avate</i></p>
			<p><i>avano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>iai</i></p>
			<p><i>iasti</i></p>
			<p><i>iò</i></p>
			<p><i>iammo</i></p>
			<p><i>iaste</i></p>
			<p><i>iarono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i>amo</i></p>
			<p><i>ate</i></p>
			<p><i>no</i></p>
		</present>
		<imperfect>
			<p><i>iassi</i></p>
			<p><i>iassi</i></p>
			<p><i>iasse</i></p>
			<p><i>iassimo</i></p>
			<p><i>iaste</i></p>
			<p><i>iassero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>a</i></p>
			<p><i></i></p>
			<p><i>amo</i></p>
			<p><i>ate</i></p>
			<p><i>no</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ante</i></p>
		</present-participle>
		<past-participle>
			<p><i>ato</i></p>
			<p><i>ati</i></p>
			<p><i>ata</i></p>
			<p><i>ate</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>ando</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="cred:ere">  <!-- 2ème groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>ere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i>i</i></p>
			<p><i>e</i></p>
			<p><i>iamo</i></p>
			<p><i>ete</i></p>
			<p><i>ono</i></p>
		</present>
		<imperfect>
			<p><i>evo</i></p>
			<p><i>evi</i></p>
			<p><i>eva</i></p>
			<p><i>evamo</i></p>
			<p><i>evate</i></p>
			<p><i>evano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>etti</i><i> ei</i></p>
			<p><i>esti</i></p>
			<p><i>ette</i><i> é</i></p>
			<p><i>emmo</i></p>
			<p><i>este</i></p>
			<p><i>ettero</i><i> erono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ano</i></p>
		</present>
		<imperfect>
			<p><i>essi</i></p>
			<p><i>essi</i></p>
			<p><i>esse</i></p>
			<p><i>essimo</i></p>
			<p><i>este</i></p>
			<p><i>essero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>i</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>ete</i></p>
			<p><i>ano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>uto</i></p>
			<p><i>uti</i></p>
			<p><i>uta</i></p>
			<p><i>ute</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>endo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="le:ggere">  <!-- 2ème groupe (exception) -->
	<infinitive>
		<infinitive-present>
			<p><i>ggere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>ggo</i></p>
			<p><i>ggi</i></p>
			<p><i>gge</i></p>
			<p><i>ggiamo</i></p>
			<p><i>ggete</i></p>
			<p><i>ggono</i></p>
		</present>
		<imperfect>
			<p><i>ggevo</i></p>
			<p><i>ggevi</i></p>
			<p><i>ggeva</i></p>
			<p><i>ggevamo</i></p>
			<p><i>ggevate</i></p>
			<p><i>ggevano</i></p>
		</imperfect>
		<future>
			<p><i>ggerò</i></p>
			<p><i>ggerai</i></p>
			<p><i>ggerà</i></p>
			<p><i>ggeremo</i></p>
			<p><i>ggerete</i></p>
			<p><i>ggeranno</i></p>
		</future>
		<simple-past>
			<p><i>ssi</i><i>ei</i></p>
			<p><i>ggesti</i></p>
			<p><i>sse</i><i>é</i></p>
			<p><i>ggemmo</i></p>
			<p><i>ggeste</i></p>
			<p><i>ssero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>ggerei</i></p>
			<p><i>ggeresti</i></p>
			<p><i>ggerebbe</i></p>
			<p><i>ggeremmo</i></p>
			<p><i>ggereste</i></p>
			<p><i>ggerebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>gga</i></p>
			<p><i>gga</i></p>
			<p><i>gga</i></p>
			<p><i>ggiamo</i></p>
			<p><i>ggiate</i></p>
			<p><i>ggano</i></p>
		</present>
		<imperfect>
			<p><i>ggessi</i></p>
			<p><i>ggessi</i></p>
			<p><i>ggesse</i></p>
			<p><i>ggessimo</i></p>
			<p><i>ggeste</i></p>
			<p><i>ggessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>ggi</i></p>
			<p><i>gga</i></p>
			<p><i>ggiamo</i></p>
			<p><i>ggete</i></p>
			<p><i>ggano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ggente</i></p>
		</present-participle>
		<past-participle>
			<p><i>tto</i></p>
			<p><i>tti</i></p>
			<p><i>tta</i></p>
			<p><i>tte</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>ggendo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="m:ettere">  <!-- 2ème groupe (exc) -->
	<infinitive>
		<infinitive-present>
			<p><i>ettere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>etto</i></p>
			<p><i>etti</i></p>
			<p><i>ette</i></p>
			<p><i>ettiamo</i></p>
			<p><i>ettete</i></p>
			<p><i>ettono</i></p>
		</present>
		<imperfect>
			<p><i>ettevo</i></p>
			<p><i>ettevi</i></p>
			<p><i>etteva</i></p>
			<p><i>ettevamo</i></p>
			<p><i>ettevate</i></p>
			<p><i>ettevano</i></p>
		</imperfect>
		<future>
			<p><i>etterò</i></p>
			<p><i>etterai</i></p>
			<p><i>etterà</i></p>
			<p><i>etteremo</i></p>
			<p><i>etterete</i></p>
			<p><i>etteranno</i></p>
		</future>
		<simple-past>
			<p><i>isi</i></p>
			<p><i>ettesti</i></p>
			<p><i>ise</i></p>
			<p><i>ettemmo</i></p>
			<p><i>etteste</i></p>
			<p><i>isero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>etterei</i></p>
			<p><i>etteresti</i></p>
			<p><i>etterebbe</i></p>
			<p><i>etteremmo</i></p>
			<p><i>ettereste</i></p>
			<p><i>etterebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>etta</i></p>
			<p><i>etta</i></p>
			<p><i>etta</i></p>
			<p><i>ettiamo</i></p>
			<p><i>ettiate</i></p>
			<p><i>ettano</i></p>
		</present>
		<imperfect>
			<p><i>ettessi</i></p>
			<p><i>ettessi</i></p>
			<p><i>ettesse</i></p>
			<p><i>ettessimo</i></p>
			<p><i>etteste</i></p>
			<p><i>ettessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>i</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>ete</i></p>
			<p><i>ano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ettente</i></p>
		</present-participle>
		<past-participle>
			<p><i>esso</i></p>
			<p><i>essi</i></p>
			<p><i>essa</i></p>
			<p><i>esse</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>ettendo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="v:edere">  <!-- 2ème groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>edere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>edo</i><i>eggo</i></p>
			<p><i>edi</i></p>
			<p><i>ede</i></p>
			<p><i>ediamo</i></p>
			<p><i>edete</i></p>
			<p><i>edono</i></p>
		</present>
		<imperfect>
			<p><i>edevo</i></p>
			<p><i>edevi</i></p>
			<p><i>edeva</i></p>
			<p><i>edevamo</i></p>
			<p><i>edevate</i></p>
			<p><i>edevano</i></p>
		</imperfect>
		<future>
			<p><i>ederò</i><i>edrò</i></p>
			<p><i>ederai</i><i>edrai</i></p>
			<p><i>ederà</i><i>edrà</i></p>
			<p><i>ederemo</i><i>edremo</i></p>
			<p><i>ederete</i><i>edrete</i></p>
			<p><i>ederanno</i><i>edranno</i></p>
		</future>
		<simple-past>
			<p><i>edetti</i><i>idi</i></p>
			<p><i>edesti</i></p>
			<p><i>edette</i><i>ide</i></p>
			<p><i>edemmo</i></p>
			<p><i>edeste</i></p>
			<p><i>edettero</i><i>ederono</i><i>idero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>edrei</i></p>
			<p><i>edresti</i></p>
			<p><i>edrebbe</i></p>
			<p><i>edremmo</i></p>
			<p><i>edreste</i></p>
			<p><i>edrebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>eda</i></p>
			<p><i>eda</i></p>
			<p><i>eda</i></p>
			<p><i>ediamo</i></p>
			<p><i>ediate</i></p>
			<p><i>edano</i></p>
		</present>
		<imperfect>
			<p><i>edessi</i></p>
			<p><i>edessi</i></p>
			<p><i>edesse</i></p>
			<p><i>edessimo</i></p>
			<p><i>edeste</i></p>
			<p><i>edessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>edi</i></p>
			<p><i>eda</i></p>
			<p><i>ediamo</i></p>
			<p><i>edete</i></p>
			<p><i>edano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>edente</i><i>eggente</i></p>
		</present-participle>
		<past-participle>
			<p><i>eduto</i><i>isto</i></p>
			<p><i>eduti</i><i>isti</i></p>
			<p><i>eduta</i><i>ista</i></p>
			<p><i>edute</i><i>iste</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>edendo</i><i>eggendo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="piac:ere">  <!-- 2ème groupe -->
	<infinitive>
		<infinitive-present>
			<p><i>ere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>cio</i></p>
			<p><i>i</i></p>
			<p><i>e</i></p>
			<p><i>iamo</i><i>ciamo</i></p>
			<p><i>ete</i></p>
			<p><i>iono</i><i>ciono</i></p>
		</present>
		<imperfect>
			<p><i>evo</i></p>
			<p><i>evi</i></p>
			<p><i>eva</i></p>
			<p><i>evamo</i></p>
			<p><i>evate</i></p>
			<p><i>evano</i></p>
		</imperfect>
		<future>
			<p><i>erò</i></p>
			<p><i>erai</i></p>
			<p><i>erà</i></p>
			<p><i>eremo</i></p>
			<p><i>erete</i></p>
			<p><i>eranno</i></p>
		</future>
		<simple-past>
			<p><i>qui</i></p>
			<p><i>esti</i></p>
			<p><i>que</i></p>
			<p><i>emmo</i></p>
			<p><i>este</i></p>
			<p><i>quero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>erei</i></p>
			<p><i>eresti</i></p>
			<p><i>erebbe</i></p>
			<p><i>eremmo</i></p>
			<p><i>ereste</i></p>
			<p><i>erebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>cia</i></p>
			<p><i>cia</i></p>
			<p><i>cia</i></p>
			<p><i>ciamo</i><i>iamo</i></p>
			<p><i>ciate</i><i>iate</i></p>
			<p><i>ciano</i></p>
		</present>
		<imperfect>
			<p><i>essi</i></p>
			<p><i>essi</i></p>
			<p><i>esse</i></p>
			<p><i>essimo</i></p>
			<p><i>este</i></p>
			<p><i>essero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>i</i></p>
			<p><i>cia</i></p>
			<p><i>ciamo</i></p>
			<p><i>ete</i></p>
			<p><i>iano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>iuto</i></p>
			<p><i>iuti</i></p>
			<p><i>iuta</i></p>
			<p><i>iute</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>endo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="part:ire">  <!-- 3ème groupe (a)-->
	<infinitive>
		<infinitive-present>
			<p><i>ire</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i>i</i></p>
			<p><i>e</i></p>
			<p><i>iamo</i></p>
			<p><i>ite</i></p>
			<p><i>ono</i></p>
		</present>
		<imperfect>
			<p><i>ivo</i></p>
			<p><i>ivi</i></p>
			<p><i>iva</i></p>
			<p><i>ivamo</i></p>
			<p><i>ivate</i></p>
			<p><i>ivano</i></p>
		</imperfect>
		<future>
			<p><i>irò</i></p>
			<p><i>irai</i></p>
			<p><i>irà</i></p>
			<p><i>iremo</i></p>
			<p><i>irete</i></p>
			<p><i>iranno</i></p>
		</future>
		<simple-past>
			<p><i>ii</i></p>
			<p><i>isti</i></p>
			<p><i>ì</i></p>
			<p><i>immo</i></p>
			<p><i>iste</i></p>
			<p><i>irono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>irei</i></p>
			<p><i>iresti</i></p>
			<p><i>irebbe</i></p>
			<p><i>iremmo</i></p>
			<p><i>ireste</i></p>
			<p><i>irebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>ano</i></p>
		</present>
		<imperfect>
			<p><i>issi</i></p>
			<p><i>issi</i></p>
			<p><i>isse</i></p>
			<p><i>issimo</i></p>
			<p><i>iste</i></p>
			<p><i>issero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>i</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>ite</i></p>
			<p><i>ano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>ito</i></p>
			<p><i>iti</i></p>
			<p><i>ita</i></p>
			<p><i>ite</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>endo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="fin:ire">  <!-- 3ème groupe (b)-->
	<infinitive>
		<infinitive-present>
			<p><i>ire</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>isco</i></p>
			<p><i>isci</i></p>
			<p><i>isce</i></p>
			<p><i>iamo</i></p>
			<p><i>ite</i></p>
			<p><i>iscono</i></p>
		</present>
		<imperfect>
			<p><i>ivo</i></p>
			<p><i>ivi</i></p>
			<p><i>iva</i></p>
			<p><i>ivamo</i></p>
			<p><i>ivate</i></p>
			<p><i>ivano</i></p>
		</imperfect>
		<future>
			<p><i>irò</i></p>
			<p><i>irai</i></p>
			<p><i>irà</i></p>
			<p><i>iremo</i></p>
			<p><i>irete</i></p>
			<p><i>iranno</i></p>
		</future>
		<simple-past>
			<p><i>ii</i></p>
			<p><i>isti</i></p>
			<p><i>ì</i></p>
			<p><i>immo</i></p>
			<p><i>iste</i></p>
			<p><i>irono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>irei</i></p>
			<p><i>iresti</i></p>
			<p><i>irebbe</i></p>
			<p><i>iremmo</i></p>
			<p><i>ireste</i></p>
			<p><i>irebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>isca</i></p>
			<p><i>isca</i></p>
			<p><i>isca</i></p>
			<p><i>iamo</i></p>
			<p><i>iate</i></p>
			<p><i>iscano</i></p>
		</present>
		<imperfect>
			<p><i>issi</i></p>
			<p><i>issi</i></p>
			<p><i>isse</i></p>
			<p><i>issimo</i></p>
			<p><i>iste</i></p>
			<p><i>issero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>i</i></p>
			<p><i>a</i></p>
			<p><i>iamo</i></p>
			<p><i>ite</i></p>
			<p><i>iscano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>ito</i></p>
			<p><i>iti</i></p>
			<p><i>ita</i></p>
			<p><i>ite</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>endo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name=":avere">  <!-- auxiliaire avoir-->
	<infinitive>
		<infinitive-present>
			<p><i>avere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>ho</i></p>
			<p><i>hai</i></p>
			<p><i>ha</i></p>
			<p><i>abbiamo</i></p>
			<p><i>avete</i></p>
			<p><i>hanno</i></p>
		</present>
		<imperfect>
			<p><i>avevo</i></p>
			<p><i>avevi</i></p>
			<p><i>aveva</i></p>
			<p><i>avevamo</i></p>
			<p><i>avevate</i></p>
			<p><i>avevano</i></p>
		</imperfect>
		<future>
			<p><i>avrò</i></p>
			<p><i>avrai</i></p>
			<p><i>avrà</i></p>
			<p><i>avremo</i></p>
			<p><i>avrete</i></p>
			<p><i>avranno</i></p>
		</future>
		<simple-past>
			<p><i>ebbi</i></p>
			<p><i>avesti</i></p>
			<p><i>ebbe</i></p>
			<p><i>avemmo</i></p>
			<p><i>aveste</i></p>
			<p><i>eberro</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>avrei</i></p>
			<p><i>avresti</i></p>
			<p><i>avrebbe</i></p>
			<p><i>avremmo</i></p>
			<p><i>avreste</i></p>
			<p><i>avrebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>abbia</i></p>
			<p><i>abbia</i></p>
			<p><i>abbia</i></p>
			<p><i>abbiamo</i></p>
			<p><i>abbiate</i></p>
			<p><i>abbiano</i></p>
		</present>
		<imperfect>
			<p><i>avessi</i></p>
			<p><i>avessi</i></p>
			<p><i>avesse</i></p>
			<p><i>avessimo</i></p>
			<p><i>aveste</i></p>
			<p><i>avessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>abbi</i></p>
			<p><i>abbia</i></p>
			<p><i>abbiamo</i></p>
			<p><i>abbite</i></p>
			<p><i>abbiano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>avente</i></p>
		</present-participle>
		<past-participle>
			<p><i>avuto</i></p>
			<p><i>avuti</i></p>
			<p><i>avuta</i></p>
			<p><i>avute</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>avendo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name=":essere">  <!-- auxiliaire être-->
	<infinitive>
		<infinitive-present>
			<p><i>essere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>sono</i></p>
			<p><i>sei</i></p>
			<p><i>è</i></p>
			<p><i>siamo</i></p>
			<p><i>siete</i></p>
			<p><i>sono</i></p>
		</present>
		<imperfect>
			<p><i>ero</i></p>
			<p><i>eri</i></p>
			<p><i>era</i></p>
			<p><i>eravamo</i></p>
			<p><i>eravate</i></p>
			<p><i>erano</i></p>
		</imperfect>
		<future>
			<p><i>sarò</i></p>
			<p><i>sarai</i></p>
			<p><i>sarà</i></p>
			<p><i>saremo</i></p>
			<p><i>sarete</i></p>
			<p><i>saranno</i></p>
		</future>
		<simple-past>
			<p><i>fui</i></p>
			<p><i>fosti</i></p>
			<p><i>fue</i></p>
			<p><i>fummo</i></p>
			<p><i>foste</i></p>
			<p><i>furono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>sarei</i></p>
			<p><i>saresti</i></p>
			<p><i>sarebbe</i></p>
			<p><i>saremmo</i></p>
			<p><i>sareste</i></p>
			<p><i>sarebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>sia</i></p>
			<p><i>sia</i></p>
			<p><i>sia</i></p>
			<p><i>siamo</i></p>
			<p><i>siate</i></p>
			<p><i>siano</i></p>
		</present>
		<imperfect>
			<p><i>fossi</i></p>
			<p><i>fossi</i></p>
			<p><i>fosse</i></p>
			<p><i>fossimo</i></p>
			<p><i>foste</i></p>
			<p><i>foessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>sii</i></p>
			<p><i>sia</i></p>
			<p><i>siamo</i></p>
			<p><i>siate</i></p>
			<p><i>sano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>ente</i></p>
		</present-participle>
		<past-participle>
			<p><i>stato</i></p>
			<p><i>stati</i></p>
			<p><i>stata</i></p>
			<p><i>state</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>essendo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name=":uscire">  <!-- 3ème groupe : exception -->
	<infinitive>
		<infinitive-present>
			<p><i>uscire</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>esco</i></p>
			<p><i>esci</i></p>
			<p><i>esce</i></p>
			<p><i>usciamo</i></p>
			<p><i>uscite</i></p>
			<p><i>escono</i></p>
		</present>
		<imperfect>
			<p><i>uscivo</i></p>
			<p><i>uscivi</i></p>
			<p><i>usciva</i></p>
			<p><i>uscivamo</i></p>
			<p><i>uscivate</i></p>
			<p><i>uscivano</i></p>
		</imperfect>
		<future>
			<p><i>uscirò</i></p>
			<p><i>uscirai</i></p>
			<p><i>uscirà</i></p>
			<p><i>usciremo</i></p>
			<p><i>uscirete</i></p>
			<p><i>usciranno</i></p>
		</future>
		<simple-past>
			<p><i>uscii</i></p>
			<p><i>uscirai</i></p>
			<p><i>uscirà</i></p>
			<p><i>usciremo</i></p>
			<p><i>uscirete</i></p>
			<p><i>usciranno</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>uscirei</i></p>
			<p><i>usciresti</i></p>
			<p><i>uscirebbe</i></p>
			<p><i>usciremmo</i></p>
			<p><i>uscireste</i></p>
			<p><i>uscirebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>esca</i></p>
			<p><i>esca</i></p>
			<p><i>esca</i></p>
			<p><i>usciamo</i></p>
			<p><i>usciate</i></p>
			<p><i>escano</i></p>
		</present>
		<imperfect>
			<p><i>uscissi</i></p>
			<p><i>uscissi</i></p>
			<p><i>uscisse</i></p>
			<p><i>uscissimo</i></p>
			<p><i>usciste</i></p>
			<p><i>uscissero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>esci</i></p>
			<p><i>esca</i></p>
			<p><i>usciamo</i></p>
			<p><i>uscite</i></p>
			<p><i>escano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>uscente</i></p>
		</present-participle>
		<past-participle>
			<p><i>uscito</i></p>
			<p><i>usciti</i></p>
			<p><i>uscita</i></p>
			<p><i>uscite</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>uscendo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="s:apere">  <!-- 2ème groupe : modal -->
	<infinitive>
		<infinitive-present>
			<p><i>apere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>o</i></p>
			<p><i>ai</i></p>
			<p><i>a</i></p>
			<p><i>appiamo</i></p>
			<p><i>apete</i></p>
			<p><i>anno</i></p>
		</present>
		<imperfect>
			<p><i>apevo</i></p>
			<p><i>apevi</i></p>
			<p><i>apeva</i></p>
			<p><i>apevamo</i></p>
			<p><i>apevate</i></p>
			<p><i>apevano</i></p>
		</imperfect>
		<future>
			<p><i>aprò</i></p>
			<p><i>aprai</i></p>
			<p><i>aprà</i></p>
			<p><i>apremo</i></p>
			<p><i>aprete</i></p>
			<p><i>apranno</i></p>
		</future>
		<simple-past>
			<p><i>eppi</i></p>
			<p><i>apesti</i></p>
			<p><i>eppe</i></p>
			<p><i>appemo</i></p>
			<p><i>apeste</i></p>
			<p><i>eppero</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>aprei</i></p>
			<p><i>apresti</i></p>
			<p><i>aprebbe</i></p>
			<p><i>apremmo</i></p>
			<p><i>apreste</i></p>
			<p><i>aprebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>
			<p><i>appia</i></p>
			<p><i>appia</i></p>
			<p><i>appia</i></p>
			<p><i>appiamo</i></p>
			<p><i>appiate</i></p>
			<p><i>appiano</i></p>
		</present>
		<imperfect>
			<p><i>apessi</i></p>
			<p><i>apessi</i></p>
			<p><i>apesse</i></p>
			<p><i>apessimo</i></p>
			<p><i>apeste</i></p>
			<p><i>apessero</i></p>
		</imperfect>
	</subjunctive>
	<imperative>
		<imperative-present>
			<p><i>appi</i></p>
			<p><i>appia</i></p>
			<p><i>appiamo</i></p>
			<p><i>apete</i></p>
			<p><i>appiano</i></p>
		</imperative-present>
	</imperative>
	<participle>
		<present-participle>
			<p><i>apiente</i></p>
		</present-participle>
		<past-participle>
			<p><i>aputo</i></p>
			<p><i>aputi</i></p>
			<p><i>aputa</i></p>
			<p><i>apute</i></p>
		</past-participle>
	</participle>
	<gerund>
		<present-gerund>
			<p><i>apendo</i></p>
		</present-gerund>
	</gerund>
</template>

<template name="p:otere">  <!-- 2ème groupe : modal -->
	<infinitive>
		<infinitive-present>
			<p><i>otere</i></p>
		</infinitive-present>
	</infinitive>
	<indicative>
		<present>
			<p><i>osso</i></p>
			<p><i>uoi</i></p>
			<p><i>uò</i></p>
			<p><i>ossiamo</i></p>
			<p><i>otete</i></p>
			<p><i>ossono</i></p>
		</present>
		<imperfect>
			<p><i>otevo</i></p>
			<p><i>otevi</i></p>
			<p><i>oteva</i></p>
			<p><i>otevamo</i></p>
			<p><i>otevate</i></p>
			<p><i>otevano</i></p>
		</imperfect>
		<future>
			<p><i>otrò</i></p>
			<p><i>otrai</i></p>
			<p><i>otrà</i></p>
			<p><i>otremo</i></p>
			<p><i>otrete</i></p>
			<p><i>otranno</i></p>
		</future>
		<simple-past>
			<p><i>otetti</i><i>otei</i></p>
			<p><i>otesti</i></p>
			<p><i>otette</i><i>oté</i></p>
			<p><i>ottemo</i></p>
			<p><i>oteste</i></p>
			<p><i>otettero</i><i>oterono</i></p>
		</simple-past>
	</indicative>
	<conditional>
		<present>
			<p><i>otrei</i></p>
			<p><i>otresti</i></p>
			<p><i>otrebbe</i></p>
			<p><i>otremmo</i></p>
			<p><i>otreste</i></p>
			<p><i>otrebbero</i></p>
		</present>
	</conditional>
	<subjunctive>
		<present>